---
name: V2G Liberty
version: dev
slug: v2g-liberty
description: Optimised vehicle-to-grid charging of your EV
url: https://github.com/V2G-liberty/addon-v2g-liberty
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
uart: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
